<a href="https://colab.research.google.com/github/DherandarReddy/RAG/blob/main/00-simple-local-rag.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a target="_blank" href="https://colab.research.google.com/github/mrdbourke/simple-local-rag/blob/main/00-simple-local-rag.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Create and run a local RAG pipeline from scratch

The goal of this notebook is to build a RAG (Retrieval Augmented Generation) pipeline from scratch and have it run on a local GPU.

Specifically, we'd like to be able to open a PDF file, ask questions (queries) of it and have them answered by a Large Language Model (LLM).

There are frameworks that replicate this kind of workflow, including [LlamaIndex](https://www.llamaindex.ai/) and [LangChain](https://www.langchain.com/), however, the goal of building from scratch is to be able to inspect and customize all the parts.

## What is RAG?

RAG stands for Retrieval Augmented Generation.

It was introduced in the paper [*Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks*](https://arxiv.org/abs/2005.11401).

Each step can be roughly broken down to:

* **Retrieval** - Seeking relevant information from a source given a query. For example, getting relevant passages of Wikipedia text from a database given a question.
* **Augmented** - Using the relevant retrieved information to modify an input to a generative model (e.g. an LLM).
* **Generation** - Generating an output given an input. For example, in the case of an LLM, generating a passage of text given an input prompt.

## Why RAG?

The main goal of RAG is to improve the generation outptus of LLMs.

Two primary improvements can be seen as:
1. **Preventing hallucinations** - LLMs are incredible but they are prone to potential hallucination, as in, generating something that *looks* correct but isn't. RAG pipelines can help LLMs generate more factual outputs by providing them with factual (retrieved) inputs. And even if the generated answer from a RAG pipeline doesn't seem correct, because of retrieval, you also have access to the sources where it came from.
2. **Work with custom data** - Many base LLMs are trained with internet-scale text data. This means they have a great ability to model language, however, they often lack specific knowledge. RAG systems can provide LLMs with domain-specific data such as medical information or company documentation and thus customized their outputs to suit specific use cases.

The authors of the original RAG paper mentioned above outlined these two points in their discussion.

> This work offers several positive societal benefits over previous work: the fact that it is more
strongly grounded in real factual knowledge (in this case Wikipedia) makes it “hallucinate” less
with generations that are more factual, and offers more control and interpretability. RAG could be
employed in a wide variety of scenarios with direct benefit to society, for example by endowing it
with a medical index and asking it open-domain questions on that topic, or by helping people be more
effective at their jobs.

RAG can also be a much quicker solution to implement than fine-tuning an LLM on specific data.


## What kind of problems can RAG be used for?

RAG can help anywhere there is a specific set of information that an LLM may not have in its training data (e.g. anything not publicly accessible on the internet).

For example you could use RAG for:
* **Customer support Q&A chat** - By treating your existing customer support documentation as a resource, when a customer asks a question, you could have a system retrieve relevant documentation snippets and then have an LLM craft those snippets into an answer. Think of this as a "chatbot for your documentation". Klarna, a large financial company, [uses a system like this](https://www.klarna.com/international/press/klarna-ai-assistant-handles-two-thirds-of-customer-service-chats-in-its-first-month/) to save $40M per year on customer support costs.
* **Email chain analysis** - Let's say you're an insurance company with long threads of emails between customers and insurance agents. Instead of searching through each individual email, you could retrieve relevant passages and have an LLM create strucutred outputs of insurance claims.
* **Company internal documentation chat** - If you've worked at a large company, you know how hard it can be to get an answer sometimes. Why not let a RAG system index your company information and have an LLM answer questions you may have? The benefit of RAG is that you will have references to resources to learn more if the LLM answer doesn't suffice.
* **Textbook Q&A** - Let's say you're studying for your exams and constantly flicking through a large textbook looking for answers to your quesitons. RAG can help provide answers as well as references to learn more.

All of these have the common theme of retrieving relevant resources and then presenting them in an understandable way using an LLM.

From this angle, you can consider an LLM a calculator for words.

## Why local?

Privacy, speed, cost.

Running locally means you use your own hardware.

From a privacy standpoint, this means you don't have send potentially sensitive data to an API.

From a speed standpoint, it means you won't necessarily have to wait for an API queue or downtime, if your hardware is running, the pipeline can run.

And from a cost standpoint, running on your own hardware often has a heavier starting cost but little to no costs after that.

Performance wise, LLM APIs may still perform better than an open-source model running locally on general tasks but there are more and more examples appearing of smaller, focused models outperforming larger models.

## Key terms

| Term | Description |
| ----- | ----- |
| **Token** | A sub-word piece of text. For example, "hello, world!" could be split into ["hello", ",", "world", "!"]. A token can be a whole word,<br> part of a word or group of punctuation characters. 1 token ~= 4 characters in English, 100 tokens ~= 75 words.<br> Text gets broken into tokens before being passed to an LLM. |
| **Embedding** | A learned numerical representation of a piece of data. For example, a sentence of text could be represented by a vector with<br> 768 values. Similar pieces of text (in meaning) will ideally have similar values. |
| **Embedding model** | A model designed to accept input data and output a numerical representation. For example, a text embedding model may take in 384 <br>tokens of text and turn it into a vector of size 768. An embedding model can and often is different to an LLM model. |
| **Similarity search/vector search** | Similarity search/vector search aims to find two vectors which are close together in high-demensional space. For example, <br>two pieces of similar text passed through an embedding model should have a high similarity score, whereas two pieces of text about<br> different topics will have a lower similarity score. Common similarity score measures are dot product and cosine similarity. |
| **Large Language Model (LLM)** | A model which has been trained to numerically represent the patterns in text. A generative LLM will continue a sequence when given a sequence. <br>For example, given a sequence of the text "hello, world!", a genertive LLM may produce "we're going to build a RAG pipeline today!".<br> This generation will be highly dependant on the training data and prompt. |
| **LLM context window** | The number of tokens a LLM can accept as input. For example, as of March 2024, GPT-4 has a default context window of 32k tokens<br> (about 96 pages of text) but can go up to 128k if needed. A recent open-source LLM from Google, Gemma (March 2024) has a context<br> window of 8,192 tokens (about 24 pages of text). A higher context window means an LLM can accept more relevant information<br> to assist with a query. For example, in a RAG pipeline, if a model has a larger context window, it can accept more reference items<br> from the retrieval system to aid with its generation. |
| **Prompt** | A common term for describing the input to a generative LLM. The idea of "[prompt engineering](https://en.wikipedia.org/wiki/Prompt_engineering)" is to structure a text-based<br> (or potentially image-based as well) input to a generative LLM in a specific way so that the generated output is ideal. This technique is<br> possible because of a LLMs capacity for in-context learning, as in, it is able to use its representation of language to breakdown <br>the prompt and recognize what a suitable output may be (note: the output of LLMs is probable, so terms like "may output" are used). |

 ## What we're going to build

We're going to build RAG pipeline which enables us to chat with a PDF document, specifically an open-source [nutrition textbook](https://pressbooks.oer.hawaii.edu/humannutrition2/), ~1200 pages long.

You could call our project NutriChat!

We'll write the code to:
1. Open a PDF document (you could use almost any PDF here).
2. Format the text of the PDF textbook ready for an embedding model (this process is known as text splitting/chunking).
3. Embed all of the chunks of text in the textbook and turn them into numerical representation which we can store for later.
4. Build a retrieval system that uses vector search to find relevant chunks of text based on a query.
5. Create a prompt that incorporates the retrieved pieces of text.
6. Generate an answer to a query based on passages from the textbook.

The above steps can broken down into two major sections:
1. Document preprocessing/embedding creation (steps 1-3).
2. Search and answer (steps 4-6).

And that's the structure we'll follow.

It's similar to the workflow outlined on the NVIDIA blog which [details a local RAG pipeline](https://developer.nvidia.com/blog/rag-101-demystifying-retrieval-augmented-generation-pipelines/).

<img src="https://github.com/mrdbourke/simple-local-rag/blob/main/images/simple-local-rag-workflow-flowchart.png?raw=true" alt="flowchart of a local RAG workflow" />

## Requirements and setup

* Local NVIDIA GPU (I used a NVIDIA RTX 4090 on a Windows 11 machine) or Google Colab with access to a GPU.
* Environment setup (see [setup details on GitHub](https://github.com/mrdbourke/simple-local-rag/?tab=readme-ov-file#setup)).
* Data source (for example, a PDF).
* Internet connection (to download the models, but once you have them, it'll run offline).

In [ ]:
# Perform Google Colab installs (if running in Google Colab)
import os

if "COLAB_GPU" in os.environ:
    print("[INFO] Running in Google Colab, installing requirements.")
    !pip install -U torch # requires torch 2.1.1+ (for efficient sdpa implementation)
    !pip install PyMuPDF # for reading PDFs with Python
    !pip install tqdm # for progress bars
    !pip install sentence-transformers # for embedding models
    !pip install accelerate # for quantization model loading
    !pip install bitsandbytes # for quantizing models (less storage space)
    !pip install flash-attn --no-build-isolation # for faster attention mechanism = faster LLM inference

## 1. Document/Text Processing and Embedding Creation

Ingredients:
* PDF document of choice.
* Embedding model of choice.

Steps:
1. Import PDF document.
2. Process text for embedding (e.g. split into chunks of sentences).
3. Embed text chunks with embedding model.
4. Save embeddings to file for later use (embeddings will store on file for many years or until you lose your hard drive).

### Import PDF Document

This will work with many other kinds of documents.

However, we'll start with PDF since many people have PDFs.

But just keep in mind, text files, email chains, support documentation, articles and more can also work.

We're going to pretend we're nutrition students at the University of Hawai'i, reading through the open-source PDF textbook [*Human Nutrition: 2020 Edition*](https://pressbooks.oer.hawaii.edu/humannutrition2/).

There are several libraries to open PDFs with Python but I found that [PyMuPDF](https://github.com/pymupdf/pymupdf) works quite well in many cases.

First we'll download the PDF if it doesn't exist.

In [ ]:
# Download PDF file
import os
import requests

# Get PDF document
pdf_path = "human-nutrition-text.pdf"

# Download PDF if it doesn't already exist
if not os.path.exists(pdf_path):
  print("File doesn't exist, downloading...")

  # The URL of the PDF you want to download
  url = "https://pressbooks.oer.hawaii.edu/humannutrition2/open/download?type=pdf"

  # The local filename to save the downloaded file
  filename = pdf_path

  # Send a GET request to the URL
  response = requests.get(url)

  # Check if the request was successful
  if response.status_code == 200:
      # Open a file in binary write mode and save the content to it
      with open(filename, "wb") as file:
          file.write(response.content)
      print(f"The file has been downloaded and saved as {filename}")
  else:
      print(f"Failed to download the file. Status code: {response.status_code}")
else:
  print(f"File {pdf_path} exists.")

File human-nutrition-text.pdf exists.

PDF acquired!

We can import the pages of our PDF to text by first defining the PDF path and then opening and reading it with PyMuPDF (`import fitz`).

We'll write a small helper function to preprocess the text as it gets read. Note that not all text will be read in the same so keep this in mind for when you prepare your text.

We'll save each page to a dictionary and then append that dictionary to a list for ease of use later.

In [ ]:
# Requires !pip install PyMuPDF, see: https://github.com/pymupdf/pymupdf
import fitz # (pymupdf, found this is better than pypdf for our use case, note: licence is AGPL-3.0, keep that in mind if you want to use any code commercially)
from tqdm.auto import tqdm # for progress bars, requires !pip install tqdm

def text_formatter(text: str) -> str:
    """Performs minor formatting on text."""
    cleaned_text = text.replace("\n", " ").strip() # note: this might be different for each doc (best to experiment)

    # Other potential text formatting functions can go here
    return cleaned_text

# Open PDF and get lines/pages
# Note: this only focuses on text, rather than images/figures etc
def open_and_read_pdf(pdf_path: str) -> list[dict]:
    """
    Opens a PDF file, reads its text content page by page, and collects statistics.

    Parameters:
        pdf_path (str): The file path to the PDF document to be opened and read.

    Returns:
        list[dict]: A list of dictionaries, each containing the page number
        (adjusted), character count, word count, sentence count, token count, and the extracted text
        for each page.
    """
    doc = fitz.open(pdf_path)  # open a document
    pages_and_texts = []
    for page_number, page in tqdm(enumerate(doc)):  # iterate the document pages
        text = page.get_text()  # get plain text encoded as UTF-8
        text = text_formatter(text)
        pages_and_texts.append({"page_number": page_number - 41,  # adjust page numbers since our PDF starts on page 42
                                "page_char_count": len(text),
                                "page_word_count": len(text.split(" ")),
                                "page_sentence_count_raw": len(text.split(". ")),
                                "page_token_count": len(text) / 4,  # 1 token = ~4 chars, see: https://help.openai.com/en/articles/4936856-what-are-tokens-and-how-to-count-them
                                "text": text})
    return pages_and_texts

pages_and_texts = open_and_read_pdf(pdf_path=pdf_path)
pages_and_texts[:2]

0it [00:00, ?it/s]

[{'page_number': -41,
  'page_char_count': 29,
  'page_word_count': 4,
  'page_sentence_count_raw': 1,
  'page_token_count': 7.25,
  'text': 'Human Nutrition: 2020 Edition'},
 {'page_number': -40,
  'page_char_count': 0,
  'page_word_count': 1,
  'page_sentence_count_raw': 1,
  'page_token_count': 0.0,
  'text': ''}]

Now let's get a random sample of the pages.

In [ ]:
import random

random.sample(pages_and_texts, k=3)

[{'page_number': 84,
  'page_char_count': 1372,
  'page_word_count': 247,
  'page_sentence_count_raw': 12,
  'page_token_count': 343.0,
  'text': '“Blood Flow  Through the  Heart” by  OpenStax  College / CC  BY 3.0  The cardiovascular system is one of the eleven organ systems of  the human body. Its main function is to transport nutrients to cells  and wastes from cells (Figure 2.12 “Cardiovascular Transportation  of Nutrients”). This system consists of the heart, blood, and blood  vessels. The heart pumps the blood, and the blood is the  transportation fluid. The transportation route to all tissues, a highly  intricate blood-vessel network, comprises arteries, veins, and  capillaries. Nutrients absorbed in the small intestine travel mainly to  the liver through the hepatic portal vein. From the liver, nutrients  travel upward through the inferior vena cava blood vessel to the  heart. The heart forcefully pumps the nutrient-rich blood first to  the lungs to pick up some oxygen and then to all other cells in  the body. Arteries become smaller and smaller on their way to  cells, so that by the time blood reaches a cell, the artery’s diameter  is extremely small and the vessel is now called a capillary. The  reduced diameter of the blood vessel substantially slows the speed  of blood flow. This dramatic reduction in blood flow gives cells time  to harvest the nutrients in blood and exchange metabolic wastes.  Figure 2.11 The Blood Flow in the Cardiovascular System  84  |  The Cardiovascular System'},
 {'page_number': 897,
  'page_char_count': 1635,
  'page_word_count': 279,
  'page_sentence_count_raw': 14,
  'page_token_count': 408.75,
  'text': 'such as watching television, playing video games, or surfing the  Internet.  Programs to address childhood obesity can include behavior  modification, exercise counseling, psychological support or  therapy, family counseling, and family meal-planning advice. For  most, the goal is not weight loss, but rather allowing height to catch  up with weight as the child continues to grow. Rapid weight loss is  not recommended for preteens or younger children due to the risk  of deficiencies and stunted growth.  Avoiding Added Sugars  One major contributing factor to childhood obesity is the  consumption of added sugars. Added sugars include not only sugar  added to food at the table, but also are ingredients in items such as  bread, cookies, cakes, pies, jams, and soft drinks. The added sugar  in store-bought items may be listed as white sugar, brown sugar,  high-fructose corn syrup, honey, malt syrup, maple syrup, molasses,  anhydrous dextrose, crystal dextrose, and concentrated fruit juice.  (Not included are sugars that occur naturally in foods, such as the  lactose in milk or the fructose in fruits.) In addition, sugars are  often “hidden” in items added to foods after they’re prepared, such  as ketchup, salad dressing, and other condiments. According to  the National Center for Health Statistics, young children and  adolescents consume an average of 322 calories per day from added  sugars, or about 16 percent of daily calories.7  7. Ervin RB, Kit BK, Carroll MD. (2012). Consumption of  Added Sugar among US Children and Adolescents,  2005–2008. National Center for Health Statistics. NCHS  Late Adolescence  |  897'},
 {'page_number': 815,
  'page_char_count': 645,
  'page_word_count': 116,
  'page_sentence_count_raw': 4,
  'page_token_count': 161.25,
  'text': 'Image by  Centers for  Disease  Control and  Prevention /  Public  Domain  Nutritional Requirements  Requirements for macronutrients and micronutrients on a per- kilogram basis are higher during infancy than at any other stage  in the human life cycle. These needs are affected by the rapid cell  division that occurs during growth, which requires energy and  protein, along with the nutrients that are involved in synthesis of  DNA and other cellular components. During this period, children  are entirely dependent on their parents or other caregivers to meet  these needs. For almost all infants six months or younger, breast  Infancy  |  815'}]

### Get some stats on the text

Let's perform a rough exploratory data analysis (EDA) to get an idea of the size of the texts (e.g. character counts, word counts etc) we're working with.

The different sizes of texts will be a good indicator into how we should split our texts.

Many embedding models have limits on the size of texts they can ingest, for example, the [`sentence-transformers`](https://www.sbert.net/docs/pretrained_models.html) model [`all-mpnet-base-v2`](https://huggingface.co/sentence-transformers/all-mpnet-base-v2) has an input size of 384 tokens.

This means that the model has been trained in ingest and turn into embeddings texts with 384 tokens (1 token ~= 4 characters ~= 0.75 words).

Texts over 384 tokens which are encoded by this model will be auotmatically reduced to 384 tokens in length, potentially losing some information.

We'll discuss this more in the embedding section.

For now, let's turn our list of dictionaries into a DataFrame and explore it.

In [ ]:
import pandas as pd

df = pd.DataFrame(pages_and_texts)
df.head()

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count,text
0,-41,29,4,1,7.25,Human Nutrition: 2020 Edition
1,-40,0,1,1,0.00,
2,-39,320,54,1,80.00,Human Nutrition: 2020 Edition UNIVERSITY OF ...
3,-38,212,32,1,53.00,Human Nutrition: 2020 Edition by University of...
4,-37,797,147,3,199.25,Contents Preface University of Hawai‘i at Mā...

In [ ]:
# Get stats
df.describe().round(2)

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count
count,1208.00,1208.00,1208.00,1208.00,1208.00
mean,562.50,1148.00,199.50,10.52,287.00
std,348.86,560.38,95.83,6.55,140.10
min,-41.00,0.00,1.00,1.00,0.00
25%,260.75,762.00,134.00,5.00,190.50
50%,562.50,1231.50,216.00,10.00,307.88
75%,864.25,1603.50,272.00,15.00,400.88
max,1166.00,2308.00,430.00,39.00,577.00

Okay, looks like our average token count per page is 287.

For this particular use case, it means we could embed an average whole page with the `all-mpnet-base-v2` model (this model has an input capacity of 384).

### Further text processing (splitting pages into sentences)

The ideal way of processing text before embedding it is still an active area of research.

A simple method I've found helpful is to break the text into chunks of sentences.

As in, chunk a page of text into groups of 5, 7, 10 or more sentences (these values are not set in stone and can be explored).

But we want to follow the workflow of:

`Ingest text -> split it into groups/chunks -> embed the groups/chunks -> use the embeddings`

Some options for splitting text into sentences:

1. Split into sentences with simple rules (e.g. split on ". " with `text = text.split(". ")`, like we did above).
2. Split into sentences with a natural language processing (NLP) library such as [spaCy](https://spacy.io/) or [nltk](https://www.nltk.org/).

Why split into sentences?

* Easier to handle than larger pages of text (especially if pages are densely filled with text).
* Can get specific and find out which group of sentences were used to help within a RAG pipeline.

> **Resource:** See [spaCy install instructions](https://spacy.io/usage).

Let's use spaCy to break our text into sentences since it's likely a bit more robust than just using `text.split(". ")`.

In [ ]:
from spacy.lang.en import English # see https://spacy.io/usage for install instructions

nlp = English()

# Add a sentencizer pipeline, see https://spacy.io/api/sentencizer/
nlp.add_pipe("sentencizer")

# Create a document instance as an example
doc = nlp("This is a sentence. This another sentence.")
assert len(list(doc.sents)) == 2

# Access the sentences of the document
list(doc.sents)

[This is a sentence., This another sentence.]

We don't necessarily need to use spaCy, however, it's an open-source library designed to do NLP tasks like this at scale.

So let's run our small sentencizing pipeline on our pages of text.

In [ ]:
for item in tqdm(pages_and_texts):
    item["sentences"] = list(nlp(item["text"]).sents)

    # Make sure all sentences are strings
    item["sentences"] = [str(sentence) for sentence in item["sentences"]]

    # Count the sentences
    item["page_sentence_count_spacy"] = len(item["sentences"])

  0%|          | 0/1208 [00:00<?, ?it/s]

In [ ]:
# Inspect an example
random.sample(pages_and_texts, k=1)

[{'page_number': 419,
  'page_char_count': 1427,
  'page_word_count': 308,
  'page_sentence_count_raw': 9,
  'page_token_count': 356.75,
  'text': 'consumed by the population, so that, on average, Americans obtain  44.6 percent of their foods in the meat and beans group from meats.  If you choose to follow a lacto-ovo vegetarian diet, the meats,  poultry, and fish can be replaced by consuming a higher percentage  of soy products, nuts, seeds, dry beans, and peas. As an aside, the  DGAC notes that these dietary patterns may not exactly align with  the typical diet patterns of people in the United States. However,  they do say that they can be adapted as a guide to develop a more  plant-based diet that does not significantly affect nutrient  adequacy.  Table 6.6 Percentage of “Meat and Beans Group” Components in  the USDA Base Diet, and Three Vegetarian Variations  Food Category  Base USDA  (%)  Plant-Based  (%)  Lacto-Ovo  Vegetarian (%)  Vegan  (%)  Meats  44.6  10.5  0  0  Poultry  27.9  8.0  0  0  Fish (high  omega-3)  2.2  3.0  0  0  Fish (low  omega-3)  7.1  10.0  0  0  Eggs  7.9  7.6  10.0  0  Soy products  0.9  15.0  30.0  25.0  Nuts and  seeds  9.4  20.9  35.0  40.0  Dry beans and  peas  n/a*  25.0  25.0  35.0  Total  100.0  100.0  100.0  100.0  *The dry beans and peas are in the vegetable food group of the base  diet.  Source:  Vegetarian Food Patterns: Food Pattern Modeling Analysis.  US  Department  of  Agriculture.  Appendix  E-3.3.  http://www.cnpp.usda.gov/Publications/DietaryGuidelines/2010/ Proteins, Diet, and Personal Choices  |  419',
  'sentences': ['consumed by the population, so that, on average, Americans obtain  44.6 percent of their foods in the meat and beans group from meats.',
   ' If you choose to follow a lacto-ovo vegetarian diet, the meats,  poultry, and fish can be replaced by consuming a higher percentage  of soy products, nuts, seeds, dry beans, and peas.',
   'As an aside, the  DGAC notes that these dietary patterns may not exactly align with  the typical diet patterns of people in the United States.',
   'However,  they do say that they can be adapted as a guide to develop a more  plant-based diet that does not significantly affect nutrient  adequacy.',
   ' Table 6.6 Percentage of “Meat and Beans Group” Components in  the USDA Base Diet, and Three Vegetarian Variations  Food Category  Base USDA  (%)  Plant-Based  (%)  Lacto-Ovo  Vegetarian (%)  Vegan  (%)  Meats  44.6  10.5  0  0  Poultry  27.9  8.0  0  0  Fish (high  omega-3)  2.2  3.0  0  0  Fish (low  omega-3)  7.1  10.0  0  0  Eggs  7.9  7.6  10.0  0  Soy products  0.9  15.0  30.0  25.0  Nuts and  seeds  9.4  20.9  35.0  40.0  Dry beans and  peas  n/a*  25.0  25.0  35.0  Total  100.0  100.0  100.0  100.0  *The dry beans and peas are in the vegetable food group of the base  diet.',
   ' Source:  Vegetarian Food Patterns: Food Pattern Modeling Analysis.',
   ' US  Department  of  Agriculture.',
   ' Appendix  E-3.3.',
   ' http://www.cnpp.usda.gov/Publications/DietaryGuidelines/2010/ Proteins, Diet, and Personal Choices  |  419'],
  'page_sentence_count_spacy': 9}]

Wonderful!

Now let's turn out list of dictionaries into a DataFrame and get some stats.

In [ ]:
df = pd.DataFrame(pages_and_texts)
df.describe().round(2)

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count,page_sentence_count_spacy
count,1208.00,1208.00,1208.00,1208.00,1208.00,1208.00
mean,562.50,1148.00,199.50,10.52,287.00,10.32
std,348.86,560.38,95.83,6.55,140.10,6.30
min,-41.00,0.00,1.00,1.00,0.00,0.00
25%,260.75,762.00,134.00,5.00,190.50,5.00
50%,562.50,1231.50,216.00,10.00,307.88,10.00
75%,864.25,1603.50,272.00,15.00,400.88,15.00
max,1166.00,2308.00,430.00,39.00,577.00,28.00

For our set of text, it looks like our raw sentence count (e.g. splitting on `". "`) is quite close to what spaCy came up with.

Now we've got our text split into sentences, how about we gorup those sentences?

### Chunking our sentences together

Let's take a step to break down our list of sentences/text into smaller chunks.

As you might've guessed, this process is referred to as **chunking**.

Why do we do this?

1. Easier to manage similar sized chunks of text.
2. Don't overload the embedding models capacity for tokens (e.g. if an embedding model has a capacity of 384 tokens, there could be information loss if you try to embed a sequence of 400+ tokens).
3. Our LLM context window (the amount of tokens an LLM can take in) may be limited and requires compute power so we want to make sure we're using it as well as possible.

Something to note is that there are many different ways emerging for creating chunks of information/text.

For now, we're going to keep it simple and break our pages of sentences into groups of 10 (this number is arbitrary and can be changed, I just picked it because it seemed to line up well with our embedding model capacity of 384).

On average each of our pages has 10 sentences.

And an average total of 287 tokens per page.

So our groups of 10 sentences will also be ~287 tokens long.

This gives us plenty of room for the text to embedded by our `all-mpnet-base-v2` model (it has a capacity of 384 tokens).

To split our groups of sentences into chunks of 10 or less, let's create a function which accepts a list as input and recursively breaks into down into sublists of a specified size.

In [ ]:
# Define split size to turn groups of sentences into chunks
num_sentence_chunk_size = 10

# Create a function that recursively splits a list into desired sizes
def split_list(input_list: list,
               slice_size: int) -> list[list[str]]:
    """
    Splits the input_list into sublists of size slice_size (or as close as possible).

    For example, a list of 17 sentences would be split into two lists of [[10], [7]]
    """
    return [input_list[i:i + slice_size] for i in range(0, len(input_list), slice_size)]

# Loop through pages and texts and split sentences into chunks
for item in tqdm(pages_and_texts):
    item["sentence_chunks"] = split_list(input_list=item["sentences"],
                                         slice_size=num_sentence_chunk_size)
    item["num_chunks"] = len(item["sentence_chunks"])

  0%|          | 0/1208 [00:00<?, ?it/s]

In [ ]:
# Sample an example from the group (note: many samples have only 1 chunk as they have <=10 sentences total)
random.sample(pages_and_texts, k=1)

[{'page_number': 1074,
  'page_char_count': 1748,
  'page_word_count': 292,
  'page_sentence_count_raw': 22,
  'page_token_count': 437.0,
  'text': 'connection to body cues of hunger and fullness and the selection  of foods based on both pleasure and nutrient density.24  When an  individual is able to disconnect from diet culture and a focus on  weight loss, they are able to eat in ways that support having energy  throughout the day and feel competent around all foods.  Instead  of an outward focus on counting calories, dietary restriction, and  measuring food portions, intuitive eating teaches a mindfulness  practice of going inward and learning to respond to the cues and  rhythms of the body.  A review of 22 intervention studies that  compared traditional weight loss to the intuitive eating approach  concluded that the participants in the non-diet groups were able  to stop unhealthy weight controlling behaviors, improve metabolic  fitness and reduce risk factors, increase body satisfaction, and  improve psychological distress.25  While the non-diet approach has  not been shown to promote weight loss, a review of clinical trials  concluded that intuitive eating was able to stabilize weight and help  to prevent future weight gain, in addition to an improvement in  blood pressure and cholesterol levels, and dietary intake.26  24. The Original Intuitive Eating Pros. (2007 - 2019). 10  Principles of Intuitive Eating.  https://www.intuitiveeating.org/10-principles-of- intuitive-eating/  25. Schaefer J. T., Magnuson A. B. (2014). A review of  interventions that promote eating my internal cues.  Journal of the Academy of Nutrition and Dietetics. 114(5),  734-760.  26. Van Dyke N., Drinkwater E. J. (2014). Relationships  between intuitive eating and health indicators:  Literature review. Public Health Nutrition. 17(8),  1757-1766.  1074  |  Calories In Versus Calories Out',
  'sentences': ['connection to body cues of hunger and fullness and the selection  of foods based on both pleasure and nutrient density.24  When an  individual is able to disconnect from diet culture and a focus on  weight loss, they are able to eat in ways that support having energy  throughout the day and feel competent around all foods.',
   ' Instead  of an outward focus on counting calories, dietary restriction, and  measuring food portions, intuitive eating teaches a mindfulness  practice of going inward and learning to respond to the cues and  rhythms of the body.',
   ' A review of 22 intervention studies that  compared traditional weight loss to the intuitive eating approach  concluded that the participants in the non-diet groups were able  to stop unhealthy weight controlling behaviors, improve metabolic  fitness and reduce risk factors, increase body satisfaction, and  improve psychological distress.25  While the non-diet approach has  not been shown to promote weight loss, a review of clinical trials  concluded that intuitive eating was able to stabilize weight and help  to prevent future weight gain, in addition to an improvement in  blood pressure and cholesterol levels, and dietary intake.26  24.',
   'The Original Intuitive Eating Pros. (',
   '2007 - 2019).',
   '10  Principles of Intuitive Eating.',
   ' https://www.intuitiveeating.org/10-principles-of- intuitive-eating/  25.',
   'Schaefer J. T., Magnuson A. B. (2014).',
   'A review of  interventions that promote eating my internal cues.',
   ' Journal of the Academy of Nutrition and Dietetics.',
   '114(5),  734-760.',
   ' 26.',
   'Van Dyke N., Drinkwater E. J. (2014).',
   'Relationships  between intuitive eating and health indicators:  Literature review.',
   'Public Health Nutrition.',
   '17(8),  1757-1766.',
   ' 1074  |  Calories In Versus Calories Out'],
  'page_sentence_count_spacy': 17,
  'sentence_chunks': [['connection to body cues of hunger and fullness and the selection  of foods based on both pleasure and nutrient density.24  When an  individual is able to disconnect from diet culture and a focus on  weight loss, they are able to eat in ways that support having energy  throughout the day and feel competent around all foods.',
    ' Instead  of an outward focus on counting calories, dietary restriction, and  measuring food portions, intuitive eating teaches a mindfulness  practice of going inward and learning to respond to the cues and  rhythms of the body.',
    ' A review of 22 intervention studies that  compared traditional weight loss to the intuitive eating approach  concluded that the participants in the non-diet groups were able  to stop unhealthy weight controlling behaviors, improve metabolic  fitness and reduce risk factors, increase body satisfaction, and  improve psychological distress.25  While the non-diet approach has  not been shown to promote weight loss, a review of clinical trials  concluded that intuitive eating was able to stabilize weight and help  to prevent future weight gain, in addition to an improvement in  blood pressure and cholesterol levels, and dietary intake.26  24.',
    'The Original Intuitive Eating Pros. (',
    '2007 - 2019).',
    '10  Principles of Intuitive Eating.',
    ' https://www.intuitiveeating.org/10-principles-of- intuitive-eating/  25.',
    'Schaefer J. T., Magnuson A. B. (2014).',
    'A review of  interventions that promote eating my internal cues.',
    ' Journal of the Academy of Nutrition and Dietetics.'],
   ['114(5),  734-760.',
    ' 26.',
    'Van Dyke N., Drinkwater E. J. (2014).',
    'Relationships  between intuitive eating and health indicators:  Literature review.',
    'Public Health Nutrition.',
    '17(8),  1757-1766.',
    ' 1074  |  Calories In Versus Calories Out']],
  'num_chunks': 2}]

In [ ]:
# Create a DataFrame to get stats
df = pd.DataFrame(pages_and_texts)
df.describe().round(2)

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count,page_sentence_count_spacy,num_chunks
count,1208.00,1208.00,1208.00,1208.00,1208.00,1208.00,1208.00
mean,562.50,1148.00,199.50,10.52,287.00,10.32,1.53
std,348.86,560.38,95.83,6.55,140.10,6.30,0.64
min,-41.00,0.00,1.00,1.00,0.00,0.00,0.00
25%,260.75,762.00,134.00,5.00,190.50,5.00,1.00
50%,562.50,1231.50,216.00,10.00,307.88,10.00,1.00
75%,864.25,1603.50,272.00,15.00,400.88,15.00,2.00
max,1166.00,2308.00,430.00,39.00,577.00,28.00,3.00

Note how the average number of chunks is around 1.5, this is expected since many of our pages only contain an average of 10 sentences.

### Splitting each chunk into its own item

We'd like to embed each chunk of sentences into its own numerical representation.

So to keep things clean, let's create a new list of dictionaries each containing a single chunk of sentences with relative information such as page number as well statistics about each chunk.

In [ ]:
import re

# Split each chunk into its own item
pages_and_chunks = []
for item in tqdm(pages_and_texts):
    for sentence_chunk in item["sentence_chunks"]:
        chunk_dict = {}
        chunk_dict["page_number"] = item["page_number"]

        # Join the sentences together into a paragraph-like structure, aka a chunk (so they are a single string)
        joined_sentence_chunk = "".join(sentence_chunk).replace("  ", " ").strip()
        joined_sentence_chunk = re.sub(r'\.([A-Z])', r'. \1', joined_sentence_chunk) # ".A" -> ". A" for any full-stop/capital letter combo
        chunk_dict["sentence_chunk"] = joined_sentence_chunk

        # Get stats about the chunk
        chunk_dict["chunk_char_count"] = len(joined_sentence_chunk)
        chunk_dict["chunk_word_count"] = len([word for word in joined_sentence_chunk.split(" ")])
        chunk_dict["chunk_token_count"] = len(joined_sentence_chunk) / 4 # 1 token = ~4 characters

        pages_and_chunks.append(chunk_dict)

# How many chunks do we have?
len(pages_and_chunks)

  0%|          | 0/1208 [00:00<?, ?it/s]

1843

In [ ]:
# View a random sample
random.sample(pages_and_chunks, k=1)

[{'page_number': 877,
  'sentence_chunk': 'Dakota County, Minnesota.https://www.co.dakota.mn.us/ HealthFamily/HealthyLiving/DietNutrition/ Documents/ReturnFamilyMeals.doc. Updated April 30, 2012. Accessed December 4, 2017. Childhood | 877',
  'chunk_char_count': 195,
  'chunk_word_count': 16,
  'chunk_token_count': 48.75}]

Excellent!

Now we've broken our whole textbook into chunks of 10 sentences or less as well as the page number they came from.

This means we could reference a chunk of text and know its source.

Let's get some stats about our chunks.

In [ ]:
# Get stats about our chunks
df = pd.DataFrame(pages_and_chunks)
df.describe().round(2)

       page_number  chunk_char_count  chunk_word_count  chunk_token_count
count      1843.00           1843.00           1843.00            1843.00
mean        583.38            734.10            112.74             183.52
std         347.79            447.51             71.24             111.88
min         -41.00             12.00              3.00               3.00
25%         280.50            315.00             45.00              78.75
50%         586.00            745.00            115.00             186.25
75%         890.00           1118.00            173.00             279.50
max        1166.00           1830.00            297.00             457.50

Hmm looks like some of our chunks have quite a low token count.

How about we check for samples with less than 30 tokens (about the length of a sentence) and see if they are worth keeping?

In [ ]:
# Show random chunks with under 30 tokens in length
min_token_length = 30
for row in df[df["chunk_token_count"] <= min_token_length].sample(5).iterrows():
    print(f'Chunk token count: {row[1]["chunk_token_count"]} | Text: {row[1]["sentence_chunk"]}')

Chunk token count: 5.25 | Text: Young Adulthood | 907
Chunk token count: 9.0 | Text: 1088 | Nutrition, Health and Disease
Chunk token count: 12.5 | Text: https://www.fda.gov/food/ 1022 | Food Preservation
Chunk token count: 19.25 | Text: 2018). Centers for Disease Control and 998 | The Causes of Food Contamination
Chunk token count: 12.5 | Text: Figure 11.2 The Structure of Hemoglobin Iron | 655

Looks like many of these are headers and footers of different pages.

They don't seem to offer too much information.

Let's filter our DataFrame/list of dictionaries to only include chunks with over 30 tokens in length.

In [ ]:
pages_and_chunks_over_min_token_len = df[df["chunk_token_count"] > min_token_length].to_dict(orient="records")
pages_and_chunks_over_min_token_len[:2]

[{'page_number': -39,
  'sentence_chunk': 'Human Nutrition: 2020 Edition UNIVERSITY OF HAWAI‘I AT MĀNOA FOOD SCIENCE AND HUMAN NUTRITION PROGRAM ALAN TITCHENAL, SKYLAR HARA, NOEMI ARCEO CAACBAY, WILLIAM MEINKE-LAU, YA-YUN YANG, MARIE KAINOA FIALKOWSKI REVILLA, JENNIFER DRAPER, GEMADY LANGFELDER, CHERYL GIBBY, CHYNA NICOLE CHUN, AND ALLISON CALABRESE',
  'chunk_char_count': 308,
  'chunk_word_count': 42,
  'chunk_token_count': 77.0},
 {'page_number': -38,
  'sentence_chunk': 'Human Nutrition: 2020 Edition by University of Hawai‘i at Mānoa Food Science and Human Nutrition Program is licensed under a Creative Commons Attribution 4.0 International License, except where otherwise noted.',
  'chunk_char_count': 210,
  'chunk_word_count': 30,
  'chunk_token_count': 52.5}]

Smaller chunks filtered!

Time to embed our chunks of text!

### Embedding our text chunks

While humans understand text, machines understand numbers best.

An [embedding](https://vickiboykis.com/what_are_embeddings/index.html) is a broad concept.

But one of my favourite and simple definitions is "a useful numerical representation".

The most powerful thing about modern embeddings is that they are *learned* representations.

Meaning rather than directly mapping words/tokens/characters to numbers directly (e.g. `{"a": 0, "b": 1, "c": 3...}`), the numerical representation of tokens is learned by going through large corpuses of text and figuring out how different tokens relate to each other.

Ideally, embeddings of text will mean that similar meaning texts have similar numerical representation.

> **Note:** Most modern NLP models deal with "tokens" which can be considered as multiple different sizes and combinations of words and characters rather than always whole words or single characters. For example, the string `"hello world!"` gets mapped to the token values `{15339: b'hello', 1917: b' world', 0: b'!'}` using [Byte pair encoding](https://en.wikipedia.org/wiki/Byte_pair_encoding) (or BPE via OpenAI's [`tiktoken`](https://github.com/openai/tiktoken) library). Google has a tokenization library called [SentencePiece](https://github.com/google/sentencepiece).

Our goal is to turn each of our chunks into a numerical representation (an embedding vector, where a vector is a sequence of numbers arranged in order).

Once our text samples are in embedding vectors, us humans will no longer be able to understand them.

However, we don't need to.

The embedding vectors are for our computers to understand.

We'll use our computers to find patterns in the embeddings and then we can use their text mappings to further our understanding.

Enough talking, how about we import a text embedding model and see what an embedding looks like.

To do so, we'll use the [`sentence-transformers`](https://www.sbert.net/docs/installation.html) library which contains many pre-trained embedding models.

Specifically, we'll get the `all-mpnet-base-v2` model (you can see the model's intended use on the [Hugging Face model card](https://huggingface.co/sentence-transformers/all-mpnet-base-v2#intended-uses)).

In [ ]:
# Requires !pip install sentence-transformers
from sentence_transformers import SentenceTransformer
embedding_model = SentenceTransformer(model_name_or_path="all-mpnet-base-v2",
                                      device="cpu") # choose the device to load the model to (note: GPU will often be *much* faster than CPU)

# Create a list of sentences to turn into numbers
sentences = [
    "The Sentences Transformers library provides an easy and open-source way to create embeddings.",
    "Sentences can be embedded one by one or as a list of strings.",
    "Embeddings are one of the most powerful concepts in machine learning!",
    "Learn to use embeddings well and you'll be well on your way to being an AI engineer."
]

# Sentences are encoded/embedded by calling model.encode()
embeddings = embedding_model.encode(sentences)
embeddings_dict = dict(zip(sentences, embeddings))

# See the embeddings
for sentence, embedding in embeddings_dict.items():
    print("Sentence:", sentence)
    print("Embedding:", embedding)
    print("")

Sentence: The Sentences Transformers library provides an easy and open-source way to create embeddings.
Embedding: [-2.07982454e-02  3.03164609e-02 -2.01217923e-02  6.86484575e-02
 -2.55255867e-02 -8.47687386e-03 -2.07212070e-04 -6.32377639e-02
  2.81606745e-02 -3.33353467e-02  3.02634109e-02  5.30721210e-02
 -5.03527038e-02  2.62288693e-02  3.33313644e-02 -4.51577567e-02
  3.63044813e-02 -1.37120159e-03 -1.20171094e-02  1.14947222e-02
  5.04510775e-02  4.70857173e-02  2.11913772e-02  5.14606424e-02
 -2.03746744e-02 -3.58889550e-02 -6.67760614e-04 -2.94393618e-02
  4.95859087e-02 -1.05639603e-02 -1.52014010e-02 -1.31759921e-03
  4.48197499e-02  1.56023111e-02  8.60379430e-07 -1.21391343e-03
 -2.37978753e-02 -9.09375725e-04  7.34487409e-03 -2.53929920e-03
  5.23370244e-02 -4.68043610e-02  1.66214723e-02  4.71579656e-02
 -4.15599272e-02  9.01959487e-04  3.60278003e-02  3.42214368e-02
  9.68227237e-02  5.94829023e-02 -1.64984372e-02 -3.51248942e-02
  5.92515618e-03 -7.07919884e-04 -2.41031293e-02  3.49740721e-02
 -2.94746570e-02  6.04268815e-03 -9.80651285e-03  2.83217859e-02
 -1.85375959e-02  3.63213159e-02  1.30292540e-02 -3.71232852e-02
  5.27256243e-02 -1.19706932e-02 -7.18082264e-02  1.24431672e-02
 -6.70565153e-03  7.42154568e-02  1.16356211e-02 -1.74533334e-02
 -1.82405449e-02 -1.88930929e-02  2.82414965e-02  1.32829025e-02
 -3.51909734e-02  8.87319213e-04  5.79572693e-02  3.22093591e-02
 -3.48583376e-03  4.13768925e-02  1.44358333e-02 -3.28044333e-02
 -9.79082379e-03 -3.16492803e-02  4.23870832e-02 -4.70846593e-02
 -2.08937023e-02 -1.91249400e-02 -1.22627355e-02  1.01606343e-02
  3.91921662e-02 -2.61896141e-02  1.09028099e-02  1.35723241e-02
 -5.79267219e-02 -3.21500227e-02 -5.75723080e-03 -2.43516192e-02
  5.23416586e-02  5.46122668e-03 -2.30996273e-02  2.57173367e-03
 -6.63346648e-02  3.54125202e-02 -1.03907483e-02  2.25410443e-02
 -1.84573643e-02 -2.42007263e-02 -4.78365682e-02 -4.79226233e-03
 -5.34138270e-02  3.01790554e-02 -1.56130763e-02 -5.51477037e-02
 -3.91874239e-02  5.92152961e-02 -3.47646959e-02  9.68120154e-03
  2.13415734e-02  2.30416805e-02  1.91713180e-02  2.77378783e-02
 -7.73507589e-03  1.04445936e-02 -2.67720185e-02 -2.40199827e-02
 -1.92290265e-02  3.91501049e-03 -2.54714675e-02  3.61942947e-02
  5.12867272e-02 -8.41693301e-03 -3.13829891e-02  1.47483349e-02
  2.13940125e-02 -3.84900682e-02  2.01944988e-02  1.20765846e-02
 -3.12067196e-03  7.84032047e-03  3.30336904e-03 -4.94357236e-02
  5.83886877e-02  3.26138176e-03  4.84485738e-03 -4.50682305e-02
  2.45682914e-02  3.55428122e-02 -5.32506108e-02  9.21152756e-02
  2.04394944e-02 -3.36951762e-02 -6.19803444e-02 -2.11038999e-02
  7.82358870e-02  5.11908047e-02  5.93170673e-02 -1.25127830e-04
  4.96350378e-02 -1.55722536e-02 -3.35680065e-03  1.82016157e-02
 -2.73444057e-02 -1.08772172e-02  1.41476458e-02  1.09877652e-02
  4.32554306e-03  8.23311135e-02 -9.85354185e-04  7.58791193e-02
  9.44996160e-03  2.37687863e-02  1.61927994e-02  6.24993294e-02
  4.75922041e-02 -3.92627763e-03  9.07524526e-02  4.49874774e-02
 -3.47131789e-02  2.14077085e-02 -3.35604288e-02  4.93849479e-02
  1.08669819e-02  2.63447762e-02 -3.26089375e-02  8.00303519e-02
  9.29764844e-03  7.16581196e-03 -2.79172380e-02 -3.06821149e-02
  4.01063403e-03 -4.93906885e-02 -3.13771330e-03  4.00537476e-02
 -3.97855230e-02  5.48013970e-02  1.36247127e-05 -8.38373303e-02
 -1.21547850e-02  3.40949968e-02  3.22405831e-03  6.11846223e-02
  5.60066774e-02  9.62873735e-03  2.54616197e-02 -4.64168899e-02
 -3.98900993e-02  7.68132210e-02  2.28408985e-02 -2.26568803e-02
 -1.91193279e-02 -6.53029159e-02  4.56781238e-02 -4.43655485e-03
  1.49631742e-02 -2.15077978e-02  2.74250261e-03  1.90358665e-02
  5.91888651e-02 -2.47569308e-02  3.66144367e-02  5.63084036e-02
 -8.86443444e-03 -1.74324550e-02 -1.03287061e-03  2.47666650e-02
  1.30762933e-02  5.04633151e-02 -5.28495526e-03  5.92397265e-02
  6.29906282e-02 -4.36783172e-02 -4.97830249e-02  5.56296594e-02
 -2.44854074e-02 -8.26754570e-02  2.04910599e-02 -1.06446259e-01
  6.64840546e-03  2.97304653e-02 -2.36440487e-02 -8.84616375e-03
  2.45555700e-03 -3.35234329e-02  7.52212331e-02 -5.89880235e-02
 -3.67808491e-02  3.41542959e-02  5.41130975e-02 -1.74904373e-02
  1.33920917e-02  4.71682772e-02  1.46115953e-02 -2.12310832e-02
 -6.55338392e-02  1.23857716e-02  2.76074540e-02 -8.02161917e-03
 -4.59636338e-02 -8.22444260e-03  9.16958041e-03 -1.56399086e-02
  7.54623115e-03  1.58309506e-03 -3.03958114e-02 -5.10671288e-02
  1.96313709e-02  1.26263117e-02 -1.51738490e-03  2.02891193e-02
  1.37817496e-02  1.49110453e-02  2.50766650e-02 -3.62870768e-02
  1.08085275e-02  2.74132914e-03  1.81510746e-02  5.39872311e-02
 -4.74542081e-02 -4.28731479e-02 -2.89914068e-02  2.13235207e-02
 -3.85161228e-02  6.31922409e-02 -5.77975884e-02  3.77887511e-03
 -2.54394282e-02 -1.77263806e-04  9.08242725e-03  1.59095172e-02
  4.11799923e-02 -3.94367687e-02 -9.64436587e-03  1.30791496e-02
  6.87962398e-02  4.32192646e-02  7.54004228e-04  6.77741393e-02
  4.93706055e-02 -3.47818411e-03 -1.06055075e-02  6.72496343e-03
 -1.39062339e-02  4.88276444e-02 -1.05734980e-02  3.50225763e-03
  2.90225470e-03  2.40044296e-02  1.20271808e-02 -2.09797528e-02
 -2.39112247e-02  3.26579213e-02 -1.01325929e-03 -5.92755107e-03
 -7.40532018e-03  3.63147026e-03 -2.26698536e-02 -2.21241675e-02
  3.86996605e-02  1.72321685e-02  3.85920107e-02 -5.04711345e-02
 -3.42145078e-02 -4.00444157e-02 -3.57910842e-02 -4.62560840e-02
  6.70232400e-02 -4.61650547e-03 -3.29677551e-03  2.08444390e-02
 -5.14257140e-03 -5.00850044e-02  2.22504158e-02  4.66933623e-02
  1.36208991e-02  1.77529808e-02  4.28078743e-03 -2.79332008e-02
 -1.93420742e-02 -3.87860052e-02 -3.09554804e-02 -6.64134398e-02
 -1.13434270e-02  1.64267439e-02  1.77629292e-02 -2.28224183e-03
 -3.30087356e-02 -1.36265485e-03 -2.17933990e-02 -2.67508384e-02
 -1.26375761e-02  1.61870918e-03 -4.95672561e-02  7.85446018e-02
  4.10962999e-02  9.65919718e-03 -1.14643425e-02  1.68855779e-03
  5.37662916e-02  2.05534603e-03 -4.11200002e-02  1.46330288e-02
 -3.75564173e-02 -3.35690081e-02  5.19256247e-03 -6.33089244e-02
  3.32963541e-02  8.76122341e-03  1.33860519e-03 -3.95748066e-03
 -1.61677618e-02  8.26747045e-02  4.75944839e-02 -3.43055166e-02
  2.50881203e-02 -3.50977108e-02  3.68657187e-02  4.12648590e-03
  4.16018143e-02 -1.35181680e-01 -4.76338044e-02 -1.20025938e-02
 -3.48891653e-02  3.25454995e-02 -2.93574738e-03 -4.85055847e-03
 -1.04223721e-01  2.78610364e-02  1.41570186e-02  3.94395366e-02
 -3.88807133e-02 -1.42463464e-02 -5.19984253e-02  8.92734993e-03
 -1.99770741e-02 -2.51725018e-02 -3.41299996e-02  1.93041582e-02
 -5.20208180e-02 -6.72000349e-02 -9.46363714e-03 -1.25584216e-03
 -5.66048585e-02  2.62098424e-02  9.91587993e-03  4.38286811e-02
  2.26644799e-03 -3.11895683e-02 -6.25467449e-02 -3.87793332e-02
 -6.83939457e-02  4.93721887e-02  5.85507713e-02 -4.08729576e-02
 -1.98638011e-02 -2.12634038e-02  4.98037338e-02 -4.51749079e-02
 -2.37141810e-02  2.32675113e-02  1.00594796e-01  9.87121277e-03
 -1.38014974e-02 -5.21041155e-02  9.08212271e-03  1.72427688e-02
  5.91431744e-02  2.62336694e-02 -7.04640476e-03 -1.50032258e-02
 -3.76659795e-03  6.28257217e-03 -5.23981489e-02 -4.96638566e-02
  3.06611136e-02 -3.33647290e-03  2.34911367e-02 -8.58830214e-02
 -4.62449901e-02  5.59701025e-02  3.09081574e-04  2.01728977e-02
 -2.98053329e-03  1.76645797e-02  1.54669918e-02 -7.41718188e-02
  7.34992046e-03 -1.05015337e-02  2.45247371e-02  1.36879105e-02
 -1.17803849e-02  4.51544710e-02  3.29039432e-02 -3.50390119e-03
 -2.71314681e-02 -5.27363941e-02 -4.60164286e-02  2.22848523e-02
  2.62271725e-02  5.56151196e-03  1.45788994e-02 -2.97145862e-02
  3.57042849e-02  2.22533848e-02  3.89616974e-02 -7.92635009e-02
 -9.01093706e-03  2.19013244e-02 -5.49054798e-03  8.69959220e-03
  4.33031246e-02 -2.12631896e-02  1.13291973e-02 -6.33699000e-02
  3.63723561e-02  2.67442502e-02 -6.64252266e-02  1.70499031e-02
 -2.79690791e-02  2.36354629e-03 -1.81953013e-02  1.52955335e-02
 -8.50433018e-03  1.16647501e-02 -9.75922048e-02 -2.92093176e-02
 -5.42547442e-02  3.61234732e-02  3.25116776e-02  8.26977100e-03
 -2.96523474e-04  1.11555932e-02 -3.85188013e-02  2.36161258e-02
  9.85921361e-03  5.73998131e-02  4.86061014e-02 -1.37579087e-02
 -6.19218173e-03  1.11972978e-02 -3.37175168e-02 -1.10515207e-02
 -7.08333626e-02 -1.01816403e-02 -3.66010703e-02 -1.55560952e-02
 -2.13110503e-02 -1.02760755e-02 -4.35733758e-02  5.55186234e-02
 -3.76548544e-02  5.29252067e-02 -3.45224105e-02 -2.43005296e-03
  7.25553185e-02  4.45072725e-03  4.71418016e-02 -9.43884999e-03
 -1.98978744e-02  5.71899749e-02  8.60541090e-02 -5.25057726e-02
 -1.39549999e-02  1.17373252e-02  1.33974161e-02 -4.73052971e-02
 -5.41674085e-02  4.62725610e-02 -2.58970186e-02  1.51415523e-02
  3.38944979e-02 -3.78259597e-03 -5.76043315e-02 -1.60082094e-02
  2.42738593e-02  3.37361023e-02 -1.96821410e-02 -2.53463909e-02
 -4.75617088e-02 -5.68755381e-02 -2.28194073e-02  3.83187421e-02
 -1.78330969e-02  1.35964137e-02  7.86004995e-04  9.74009186e-03
  3.34298909e-02 -2.60134134e-02 -7.38566089e-03  3.56451049e-02
 -2.68532336e-02 -7.53624663e-02 -2.66983863e-02 -4.46457456e-33
 -3.31646502e-02  1.41703757e-02 -3.92909572e-02 -3.46318893e-02
 -5.88670094e-03 -1.18212020e-02  1.53951440e-02  1.18473554e-02
  1.07756881e-02  3.62140276e-02  7.87954126e-03 -2.31845491e-02
  1.07623311e-02  1.72346402e-02  9.54185671e-04  2.83640325e-02
  2.37419680e-02 -1.48058087e-02  1.24199654e-03  3.52354092e-03
  2.33735722e-02  5.58308028e-02  5.38327880e-02 -3.74079235e-02
 -2.11805366e-02  1.52705179e-04 -7.27789523e-03  5.50558697e-03
  3.05823646e-02  4.54633310e-02 -3.35786641e-02  3.16142775e-02
 -2.56394874e-03  3.96355167e-02 -1.47573631e-02  5.67167625e-02
 -5.62787689e-02 -5.04600164e-03  3.56154703e-02 -2.76198648e-02
 -2.32292321e-02 -4.63292077e-02 -3.70919965e-02 -4.23188992e-02
  3.70306894e-02  7.88716506e-03  3.85176279e-02  1.74774998e-03
  5.62760606e-03  6.18106779e-03 -6.90268725e-02 -9.42963548e-03
 -7.74672301e-03  1.68350022e-02  1.22767650e-02  2.26406269e-02
  1.21009145e-02  1.11743277e-02  1.21539123e-02 -1.16862059e-02
 -4.41612639e-02  2.30047107e-02  2.20672395e-02 -5.87504469e-02
 -3.96428294e-02  6.83135316e-02 -3.29947919e-02 -3.66774611e-02
 -3.53654884e-02  1.76184997e-02  6.95639336e-03  5.92693053e-02
  4.12156135e-02  7.98109546e-02 -5.36561711e-03  1.14238923e-02
 -2.96388883e-02 -1.15411803e-02  2.22812518e-02  7.93185271e-03
  2.60356013e-02  1.28212180e-02  1.71345510e-02 -6.90186489e-03
 -1.07603315e-02  1.35714365e-02 -9.90793575e-04 -6.16075806e-02
  4.40514125e-02 -8.26588890e-04 -2.78340820e-02 -1.23619046e-02
  1.34629309e-02 -3.85745540e-02  1.08702201e-03  2.18712501e-02
 -3.32398899e-02  1.84615832e-02 -5.10112662e-03  3.74665000e-02
 -3.67542636e-03 -2.19246186e-02 -4.96481918e-03 -9.59839299e-03
  2.33590882e-02  1.04876896e-02  4.38722000e-02 -1.51424445e-02
 -6.30309433e-02  8.23259261e-03 -1.09130777e-02 -4.06409241e-02
 -6.21691048e-02  2.21326090e-02 -2.71434374e-02  4.05539535e-02
 -8.09450168e-03 -1.76411856e-03  3.01526431e-02 -5.42263594e-03
 -4.69821692e-02 -1.73768755e-02  4.11630757e-02  3.20634916e-02
 -2.22944077e-02 -1.58161949e-02 -4.50720750e-02  5.69486134e-02
  4.71595824e-02 -5.78058623e-02  1.32475067e-02 -4.71290573e-03
  1.66824478e-07  4.81090508e-02  5.03627695e-02  5.45263514e-02
  2.07568854e-02 -1.19080851e-02 -6.37492025e-03  5.26365731e-03
  7.21949488e-02 -2.21763328e-02  2.20103282e-02 -9.90472035e-04
 -1.37163652e-02  6.89206831e-03  2.46912930e-02 -1.39462054e-01
  2.56982353e-03 -4.64826524e-02 -4.04967442e-02 -6.08555786e-02
 -1.53213022e-02  1.36129886e-01  9.45034549e-02  4.25741598e-02
  4.67131250e-02 -2.30677836e-02 -1.20966146e-02  3.86672989e-02
  2.11647153e-03 -2.51473337e-02 -1.15076145e-02 -3.46506499e-02
 -2.29533613e-02 -6.33848412e-03 -3.05175930e-02 -1.56236812e-02
  1.39513770e-02  3.27480840e-04  2.00324273e-03  4.15105931e-03
 -2.22924817e-02 -3.62589881e-02 -2.36579385e-02 -1.87817290e-02
 -1.96289048e-02  4.52125929e-02 -8.12568441e-02 -2.14569159e-02
 -4.41542976e-02 -2.68475562e-02  2.01974250e-02  2.82992376e-03
 -1.95011701e-02 -3.45331058e-02  2.26913579e-02  3.78326140e-02
 -1.02544138e-02 -2.19757902e-03 -8.96744430e-02 -4.50030938e-02
  8.09700694e-03 -2.05805413e-02 -2.02998985e-02 -2.09922474e-02
 -1.79404747e-02  5.81897646e-02 -7.63651822e-03  1.50847360e-02
  1.78279744e-34  4.86179255e-02  4.22228277e-02  4.71595712e-02
  5.89047186e-02  3.99785452e-02 -5.27071394e-02  1.56905577e-02
 -5.25131356e-04  1.13652181e-02 -6.56410307e-02 -2.20849197e-02]

Sentence: Sentences can be embedded one by one or as a list of strings.
Embedding: [ 4.31717858e-02 -5.38702235e-02 -3.78044471e-02  4.27235961e-02
 -2.35408805e-02  3.44860852e-02  2.89586503e-02  1.92816986e-03
  2.41733305e-02 -3.17012630e-02  7.32856095e-02  1.25590367e-02
  3.64620462e-02 -2.05251314e-02  2.81973835e-02 -6.87328950e-02
  4.22231555e-02  9.31740215e-04  3.54035348e-02  1.41787585e-02
  7.83996563e-03  2.31178887e-02 -4.84735239e-03  1.07174013e-02
  4.39489540e-03  5.47801238e-03 -3.80338766e-02 -3.05490522e-03
  5.72229363e-03 -6.78214133e-02 -4.88007590e-02 -1.45032611e-02
  6.68013142e-03 -7.17480108e-02  1.64644814e-06  1.07564498e-02
 -3.60923149e-02 -2.37056948e-02 -5.22791520e-02  3.46110314e-02
 -5.42178797e-03  1.62611865e-02  1.96564570e-02  2.25396045e-02
 -2.26000324e-03  4.06341590e-02  8.17157403e-02  2.48179771e-02
  5.31884655e-02  7.82715008e-02 -1.91813763e-02 -1.94087215e-02
 -2.62805000e-02 -2.44082790e-02  5.49405515e-02  1.90318637e-02
  1.60811562e-02 -2.68895458e-02 -8.24694894e-03  7.33445063e-02
  1.00123324e-02  2.93315910e-02  3.42859165e-03 -2.13270076e-02
 -1.62441330e-03 -5.56254527e-03 -7.64879584e-02 -5.85450642e-02
 -2.82272082e-02  7.51847168e-03  7.11225718e-02  1.95454550e-03
  5.45930117e-03  3.22320778e-03  5.12799919e-02 -3.54106016e-02
 -5.03608584e-02  4.70518954e-02  5.15479129e-03  1.52287390e-02
 -1.06680496e-02  3.16298455e-02 -9.09040123e-03 -4.01327722e-02
 -4.35235873e-02 -1.94969308e-02  1.65604744e-02 -4.71168794e-02
 -3.92091870e-02 -3.07756979e-02 -2.94167269e-02 -4.20826450e-02
  2.27071461e-03 -2.78329421e-02  1.69421788e-02  7.74500147e-03
 -5.23741841e-02 -4.50040139e-02  3.83605063e-02 -4.90786508e-02
  5.06618954e-02  1.01615470e-02 -1.25021460e-02 -4.64554736e-03
 -1.54540222e-02  1.58862546e-02  1.18370233e-02 -3.59232761e-02
 -7.76225328e-02  3.43358591e-02 -2.14710198e-02 -6.86098784e-02
 -5.46236634e-02  7.83901736e-02 -3.00702397e-02 -3.37550379e-02
 -4.04998697e-02  4.80515659e-02  9.53901373e-03  2.31399462e-02
 -8.16115141e-02 -6.51697954e-03  1.54213300e-02  7.04257935e-02
 -1.25068957e-02 -2.48266775e-02 -1.71328336e-02  6.13106694e-03
  5.44412658e-02 -1.40566211e-02 -6.24515349e-03  3.65788303e-02
  7.36230463e-02 -6.05679816e-03 -3.61630879e-02 -1.42202468e-03
  4.43166047e-02 -3.14512243e-03  3.18767726e-02 -1.30947968e-02
 -3.69524211e-02 -4.98030707e-03  1.30019384e-03 -2.05213390e-02
  2.06277650e-02  5.93871623e-03 -3.07166809e-03 -3.97512950e-02
  4.29890119e-02  6.49802685e-02 -6.76022395e-02  5.41655645e-02
  1.52559101e-03 -3.72908749e-02 -4.02427241e-02 -2.28772555e-02
  1.31769747e-01  4.87875193e-03  1.39470687e-02  4.92435396e-02
  2.49218997e-02 -8.76090024e-03 -5.38766198e-03 -2.65595913e-02
 -1.19766314e-02 -2.32006963e-02 -2.67434083e-02  5.66911092e-03
  2.21722070e-02  4.67294008e-02 -5.78487478e-02  8.22120681e-02
 -3.36834532e-03  8.09647962e-02  1.41423400e-02  1.02393068e-01
 -5.76832984e-03 -1.15877483e-02  4.90585156e-02  5.87829575e-02
  6.50030673e-02  4.74621616e-02 -2.89464127e-02 -1.76584988e-03
  3.32561173e-02  2.91198548e-02  6.03811108e-02  3.73513234e-04
  1.06576262e-02 -5.96284606e-02 -7.28601590e-02  2.95079984e-02
  9.54463333e-03 -2.71542463e-02 -5.63305095e-02  9.66717955e-04
 -4.77729663e-02  4.67576869e-02  4.87254886e-03 -6.57519177e-02
 -1.42248394e-02  3.99872884e-02 -1.09797120e-02  7.68941566e-02
 -4.00004014e-02  2.96826195e-02  2.81303488e-02 -5.55424988e-02
  6.31262269e-03  5.00450209e-02  1.89884175e-02  5.38683757e-02
 -1.95981767e-02  1.08601097e-02  1.64150242e-02  1.44135077e-02
  1.71448775e-02  2.17625033e-02 -4.98862863e-02  1.56104807e-02
  4.83737933e-03  1.87053327e-02 -3.18541424e-03  2.66863015e-02
  5.55552803e-02 -4.88005839e-02 -3.02929282e-02  2.52110474e-02
  1.07264733e-02  1.88270416e-02 -1.50687927e-02  3.43832113e-02
  4.15125005e-02  1.37788970e-02 -5.54849058e-02  1.43849021e-02
 -5.88139631e-02 -6.01677038e-02  2.69856229e-02 -5.46130054e-02
  8.14635586e-03 -1.17758205e-02  1.57443043e-02  1.43905252e-03
 -2.64554713e-02 -4.48876470e-02  4.39732783e-02 -1.06166059e-04
 -2.25905683e-02  3.00296620e-02  1.97440535e-02  7.44078029e-03
 -1.93789750e-02  8.09798390e-03  4.34859656e-02 -1.08594213e-04
 -3.77225615e-02  2.67196093e-02 -4.63157333e-02 -1.53402903e-03
  8.05315748e-03 -4.30900641e-02 -2.13848893e-02  1.20185493e-02
  8.41401331e-03  2.48273951e-03 -3.09566837e-02 -9.05277953e-02
 -4.76693772e-02  1.22606363e-02 -1.36466948e-02 -2.63655148e-02
 -7.65549811e-03  8.72378610e-03  2.65725013e-02  8.40021472e-04
 -5.55925863e-03 -9.29540675e-03  3.19337174e-02  5.94646744e-02
  1.83205586e-02 -7.56546631e-02 -5.59389070e-02 -1.20870778e-02
 -3.16260904e-02  3.62187363e-02  7.53608532e-03 -6.15654252e-02
 -2.30459403e-02 -3.51668103e-03  1.23332245e-02 -9.67635680e-03
  4.96861972e-02 -8.42256770e-02  1.52395982e-02 -1.82445291e-02
  7.70462677e-02  9.28717479e-02  4.03724536e-02  1.11732617e-01
 -1.03270533e-02 -2.54557971e-02  2.13153847e-02 -1.16185774e-03
  2.82601011e-03  5.06967381e-02 -3.13697159e-02 -8.14268366e-03
  1.38387550e-02  4.66889776e-02  5.09670749e-02  3.77154164e-02
 -2.94988696e-02  3.60631533e-02 -2.61165947e-03  2.72287230e-04
 -6.71806633e-02 -6.54026195e-02 -3.43590938e-02  1.91067308e-02
  4.13294099e-02 -1.10970642e-02  4.51951697e-02 -5.93565442e-02
  1.06963618e-02 -1.82229858e-02 -5.65814190e-02  1.20386574e-02
  4.44773585e-02  1.87049974e-02  1.63810123e-02  5.51150478e-02
 -2.23332569e-02  2.12861896e-02 -1.20340046e-02  3.26752774e-02
  1.47004733e-02 -8.16681422e-03  1.12904878e-02 -3.00620608e-02
 -2.34345645e-02 -2.68646162e-02 -1.28718361e-03 -7.67189786e-02
  2.22609076e-03 -5.89473452e-03  2.63103917e-02  2.07128888e-03
 -6.91151991e-02 -1.43792154e-02  2.68788505e-02 -3.51539738e-02
 -2.69612148e-02  2.54716654e-03 -6.48882017e-02  3.18728238e-02
  1.70126799e-02 -4.54004295e-02 -1.80616081e-02 -1.61116198e-02
  5.70774116e-02 -2.78272200e-03 -6.45585209e-02  7.86597878e-02
  2.29075011e-02  6.81840256e-03 -9.11738817e-03 -2.27726400e-02
 -4.76526581e-02  4.88430522e-02 -2.09891740e-02 -2.43693609e-02
 -5.01207775e-03  6.70253783e-02  6.91369316e-03  2.25843024e-02
  2.51125246e-02 -6.92505995e-03  8.59400816e-03  2.38977149e-02
  3.29738371e-02 -1.05310552e-01  1.22094667e-02 -1.22263627e-02
 -5.73768876e-02  1.84311923e-02  2.97158770e-02 -6.09429069e-02
 -6.55256361e-02  3.55713032e-02  5.64321270e-03  3.34644690e-03
 -3.59686911e-02 -8.83416273e-03 -6.97894916e-02  6.89779446e-02
 -4.88214474e-03  2.23995075e-02 -3.16053368e-02 -7.41184922e-03
  3.19350846e-02 -5.18788733e-02  2.11601369e-02 -5.03340326e-02
  9.10575408e-03  2.13354621e-02  1.66838132e-02  3.49020064e-02
 -6.38499558e-02 -6.75624330e-03 -1.27405105e-02 -4.63366471e-02
 -1.14779640e-02  2.08778419e-02  2.44822092e-02  3.66461440e-03
 -2.86097336e-03  2.29390766e-02  2.13745944e-02 -3.48900966e-02
 -3.00387945e-02  4.78870198e-02  5.83370738e-02 -9.70496889e-03
  1.38234664e-02 -3.27485576e-02 -8.11483886e-04  9.54227615e-03
  1.20401271e-02  1.97230149e-02 -4.74878674e-04 -1.39226364e-02
 -5.21070324e-02 -1.75592601e-02 -5.41698560e-02 -1.17969932e-02
 -1.71030406e-02 -3.50195356e-02  3.38661671e-02 -6.76587299e-02
 -2.27606539e-02  1.95606947e-02  5.50249219e-02  1.22028943e-02
 -1.75167294e-03  7.22446060e-03  1.16350027e-02 -1.61907803e-02

Woah! That's a lot of numbers.

How about we do just once sentence?

In [ ]:
single_sentence = "Yo! How cool are embeddings?"
single_embedding = embedding_model.encode(single_sentence)
print(f"Sentence: {single_sentence}")
print(f"Embedding:\n{single_embedding}")
print(f"Embedding size: {single_embedding.shape}")

Sentence: Yo! How cool are embeddings?
Embedding:
[-1.97447948e-02 -4.51075844e-03 -4.98485751e-03  6.55444860e-02
 -9.87673178e-03  2.72836369e-02  3.66426371e-02 -3.30219069e-03
  8.50076228e-03  8.24953150e-03 -2.28498019e-02  4.02430296e-02
 -5.75200543e-02  6.33692220e-02  4.43207324e-02 -4.49506566e-02
  1.25284549e-02 -2.52011698e-02 -3.55292819e-02  1.29559152e-02
  8.67022853e-03 -1.92917623e-02  3.55634978e-03  1.89505499e-02
 -1.47128273e-02 -9.39846318e-03  7.64178485e-03  9.62185580e-03
 -5.98921441e-03 -3.90169099e-02 -5.47824912e-02 -5.67457452e-03
  1.11644482e-02  4.08067219e-02  1.76319122e-06  9.15305223e-03
 -8.77257995e-03  2.39382796e-02 -2.32784394e-02  8.04999769e-02
  3.19176950e-02  5.12598967e-03 -1.47708310e-02 -1.62525158e-02
 -6.03213087e-02 -4.35689762e-02  4.51211743e-02 -1.79053359e-02
  2.63366643e-02 -3.47867049e-02 -8.89174361e-03 -5.47675528e-02
 -1.24372616e-02 -2.38606837e-02  8.33496824e-02  5.71241863e-02
  1.13328351e-02 -1.49595067e-02  9.20378491e-02  2.72709653e-02
 -1.42185297e-02  1.91209260e-02  1.49963433e-02 -3.12198400e-02
  8.99578854e-02  4.51188385e-02  2.58020591e-02 -5.51736308e-03
  1.15909697e-02  4.72100750e-02 -1.51019115e-02  1.70818456e-02
 -7.22597120e-03  3.45763527e-02 -8.76467489e-03  5.22016883e-02
 -6.49009049e-02 -4.31378409e-02  6.36964738e-02  4.02881242e-02
 -1.99042521e-02  5.39060030e-03  1.28820706e-02 -4.81255241e-02
  4.58800793e-02 -2.17094179e-02  1.89203732e-02 -3.46344374e-02
 -1.66456550e-02  7.65164290e-03 -2.26693675e-02 -1.96454190e-02
  1.87632367e-02  1.01383114e-02  6.85413033e-02 -5.39849931e-03
 -3.38224438e-03  4.08413112e-02  4.98624146e-02 -1.16485711e-02
  8.91738757e-02  4.02785726e-02 -3.64718935e-03  4.37758788e-02
 -2.96080466e-02 -5.53755462e-03 -2.00209152e-02 -2.01982651e-02
  4.59849127e-02  2.29337532e-02 -5.37306629e-02 -3.19279395e-02
  1.37541676e-03  6.25036135e-02 -2.18308866e-02 -6.43256083e-02
 -2.24791914e-02  3.31955366e-02 -3.12837847e-02  5.17935790e-02
 -2.84003615e-02  2.55067851e-02  3.36493477e-02  7.50668347e-02
 -4.46472270e-03 -4.87705581e-02 -7.35218823e-02 -5.46352826e-02
  8.88525974e-03  2.95797568e-02 -9.95696988e-03 -6.32762676e-03
  4.46259901e-02 -1.58483926e-02 -1.71330515e-02  3.36603038e-02
 -1.57666835e-03 -5.45971766e-02  2.91160997e-02 -2.80596483e-02
  2.96793450e-02  5.12153208e-02  1.48765910e-02 -4.76488173e-02
  1.26052350e-02  1.49851048e-03  1.33206528e-02 -2.82469280e-02
 -3.29254754e-02 -8.53568502e-03 -5.27607836e-02  7.29350299e-02
 -6.41821027e-02 -2.51787063e-03 -9.02632624e-03 -1.10466534e-03
  1.57514270e-02  4.30823304e-02  1.12269390e-02 -3.54585834e-02
  4.95163053e-02  1.21270875e-02  1.66345329e-03 -5.06923534e-03
 -1.11002065e-02 -8.66926648e-03 -3.26439962e-02 -3.98021862e-02
 -2.05970760e-02  1.09074283e-02 -6.62528723e-02  3.71707082e-02
 -3.74916680e-02 -3.24730612e-02  5.85900731e-02  8.48081037e-02
  3.92412879e-02  3.15815061e-02  3.78386155e-02 -1.35472585e-02
  5.95062599e-02  2.58904994e-02 -1.31900124e-02  6.30589947e-02
  3.27136330e-02  6.92141987e-03 -1.42607167e-02  7.76676759e-02
 -1.16103226e-02 -3.66427749e-02 -2.83837821e-02  2.72279996e-02
  2.49364395e-02 -4.22296580e-03 -3.63100991e-02 -2.04887912e-02
  3.98861393e-02 -2.64726523e-02  4.41384874e-03 -5.19635342e-02
  1.71132469e-05  4.81284633e-02  2.04450581e-02  9.84969735e-02
  3.68267484e-02  1.53404996e-02  7.50985928e-04 -3.38638574e-02
 -2.69872770e-02  4.72444706e-02  4.56701443e-02 -3.49246524e-02
 -1.18770516e-02  3.45579605e-03 -6.32301252e-03 -4.78412546e-02
  1.84098575e-02 -2.23157406e-02 -3.70727852e-02  5.87340109e-02
  6.22731680e-03 -1.46715995e-02  7.29223117e-02  2.21961108e-03
 -6.53120130e-02  3.51679586e-02 -1.54901948e-02  6.01421148e-02
 -9.40999761e-03  2.81196870e-02 -1.12651652e-02  5.24140254e-04
  1.01888642e-01 -5.69957718e-02 -3.52360606e-02 -5.20477397e-03
 -8.46639927e-03  1.39209218e-02  1.80780366e-02 -1.10493958e-01
  5.13116792e-02 -4.36432101e-02  2.84142811e-02  9.55935288e-03
  4.28096801e-02 -3.95833924e-02  5.25829233e-02  1.92814860e-02
  3.44887213e-03 -1.76871512e-02  3.85700017e-02  6.92504412e-03
 -3.59440260e-02 -2.63612997e-02 -4.96697612e-03  4.24525589e-02
 -4.22464088e-02  3.45897325e-03  3.55866775e-02 -1.68202054e-02
  3.54331955e-02  4.52805124e-03  6.46287994e-03 -2.17710957e-02
 -2.50033271e-02  1.41418474e-02  1.51257729e-02 -2.99569797e-02
 -3.94227579e-02  1.87822003e-02 -1.68783998e-03 -9.83485719e-04
 -3.26322317e-02  5.06562646e-03 -8.90462752e-03 -1.55095356e-02
  1.87758338e-02 -4.52473164e-02 -1.72956996e-02  3.50973308e-02
  1.33018484e-02  1.00632990e-02 -4.36593369e-02 -1.68619286e-02
 -1.91048589e-02  6.35489672e-02  8.08326993e-03 -1.02532702e-02
 -4.53625154e-03 -4.60835956e-02 -1.64704416e-02 -6.24687178e-03
  2.58868467e-02 -6.39063865e-02 -7.82403164e-03 -2.36076415e-02
  2.74617821e-02  5.80534823e-02 -3.40748504e-02  6.46012425e-02
  2.00062692e-02 -2.14934982e-02  1.69361141e-02 -5.54071181e-03
 -2.40397565e-02  3.09444312e-02 -2.34439946e-03  3.02589163e-02
 -4.57217358e-02  2.00641491e-02 -2.57117171e-02 -1.13374600e-03
 -3.57524492e-02  6.92953542e-02  2.80848006e-03  3.58742066e-02
 -1.52722122e-02 -3.41523774e-02  1.80923492e-02  1.65400021e-02
  1.31705757e-02 -6.36672601e-03  5.49303107e-02  8.47314950e-03
 -4.26077209e-02  2.17084438e-02 -4.89023589e-02  1.18892436e-04
  5.16287498e-02  7.59213988e-04  1.59222931e-02 -1.61299668e-02
  1.44981621e-02  2.19509173e-02  3.02651469e-02 -3.44151258e-02
 -4.80380058e-02 -3.71689945e-02  4.68195081e-02 -3.46219055e-02
  4.74856875e-04 -4.34820838e-02 -1.80125032e-02 -6.44844547e-02
 -2.66967788e-02  3.63661051e-02 -3.76219675e-02 -1.64600834e-02
  2.20248699e-02  2.16068816e-04  3.64510901e-02 -2.76135951e-02
 -5.87056717e-03  6.97318790e-03 -1.25863892e-03  2.12774184e-02
  6.21474395e-03 -3.57214808e-02 -5.09366393e-02  2.85553057e-02
  6.48822486e-02  3.45731415e-02 -2.57281121e-02  4.52562002e-03
 -4.63605858e-02  3.32225412e-02  1.69971155e-03 -1.29355490e-02
 -3.03734243e-02  1.23609146e-02 -3.17948812e-04  1.66231729e-02
  1.04892310e-02  1.71540547e-02  1.88860130e-02 -3.62256356e-02
  4.65737544e-02  2.17128489e-02  4.97535430e-02  3.03067565e-02
  1.59914512e-03 -6.30024523e-02 -6.34594914e-03  1.07306470e-04
 -5.56749804e-03  2.37264745e-02 -8.38230830e-03  5.38897291e-02
 -9.08977017e-02 -1.37359807e-02  1.18454387e-02  3.37260496e-03
 -2.81855837e-02  1.56334380e-03  2.22415514e-02  6.21023998e-02
 -8.68120119e-02 -4.40636650e-03 -1.63995605e-02  1.69665124e-02
 -1.34548442e-02  3.00699519e-03 -2.14618109e-02 -2.09503602e-02
 -1.39877331e-02 -1.23850591e-02  5.39979264e-02  6.03614524e-02
  2.52982099e-02 -1.29661456e-01 -1.08081490e-01 -4.15776996e-03
 -7.20272586e-03  2.75885426e-02  4.87622246e-02 -2.95970924e-02
 -4.32555042e-02  2.75215656e-02  1.35718705e-02  3.87699939e-02
  2.42039859e-02 -2.70842370e-02  8.59166756e-02 -1.98402721e-02
 -2.26344075e-02 -6.24927692e-02 -1.56845059e-02  4.11566868e-02
  1.66952293e-02  7.97291845e-02 -3.24839242e-02  1.46562653e-03
 -3.27906236e-02  6.44815415e-02  2.09739301e-02 -7.56985918e-02
 -1.31790887e-03  2.24047410e-03 -6.60842517e-03 -6.84252009e-02
 -5.36861317e-03  6.55135959e-02  5.45556936e-03  1.58993881e-02
 -2.18052026e-02  2.16424442e-03  4.72953916e-03 -7.25655705e-02
 -1.59349535e-02 -1.05623556e-02  2.70786881e-02  1.93767296e-03
 -4.45123240e-02  2.89783329e-02  2.43084133e-02 -1.73885804e-02
 -3.80669385e-02 -3.06799058e-02 -3.24778110e-02 -4.33352252e-04
  2.55846214e-02  2.70478334e-02 -1.72536747e-04 -4.93691477e-04
 -7.12095052e-02  5.69768585e-02  6.61401227e-02 -3.87268029e-02
 -1.30683305e-02  1.00663435e-02 -2.17740107e-02  1.92212425e-02
  7.66691193e-03 -3.86652723e-02 -1.66108683e-02 -3.41468006e-02
 -1.04185399e-02  1.75906215e-02 -1.23776319e-02 -1.68433636e-02
 -2.40113325e-02  4.70198225e-03  4.88461414e-03  4.73663956e-02
  4.34111990e-02 -8.08345061e-03 -2.48272046e-02 -1.93978231e-02
 -3.16525213e-02 -1.56419240e-02 -7.79948430e-03  1.28888777e-02
  2.61943471e-02  3.65819852e-03  5.79228885e-02  5.43151535e-02
 -5.05587049e-02  1.78928417e-03 -2.45470889e-02 -2.47596093e-02
  3.60357016e-03  1.94152333e-02 -4.23822999e-02 -1.86907351e-02
  2.32945625e-02 -3.17982696e-02 -2.60645580e-02 -5.40359830e-03
 -3.82070243e-02  2.21719500e-02  1.33360438e-02  5.58054298e-02
 -3.57717127e-02 -3.54791582e-02  1.27723375e-02  6.80177361e-02
  5.37152775e-02  2.54151635e-02 -1.16638802e-02 -1.07512847e-02
 -9.74433962e-03  7.20506534e-03  9.21895634e-03 -4.73684818e-02
 -3.89390299e-03  3.11453715e-02  3.62332240e-02 -1.65902749e-02
 -3.63394916e-02  1.95634849e-02 -2.15058718e-02 -7.04764063e-03
  9.13174357e-03 -4.05359082e-02 -3.67075950e-02  1.16995975e-01
  1.17913894e-01  8.00502822e-02 -1.61983408e-02 -2.00733431e-02
 -5.54061942e-02 -7.22410455e-02  2.14558132e-02 -4.46405582e-04
 -1.42902900e-02  8.35542101e-03  3.34207751e-02  1.42891202e-02
  4.62512709e-02 -3.53420265e-02  1.68673471e-02 -2.99733435e-03
 -5.44997156e-02 -4.80719507e-02  9.47575609e-04 -6.29721654e-33
 -2.30286475e-02 -2.51128022e-02 -5.35218976e-02 -2.09470093e-02
 -6.79715117e-03 -4.64015380e-02 -4.49637184e-03  1.65114906e-02
 -1.12677943e-02  1.33013874e-02 -1.72552858e-02 -1.96653791e-02
  5.53235179e-03  1.02775507e-02  9.47372930e-04 -2.24022605e-02
  5.30364998e-02  7.77776260e-03 -9.48473252e-03  2.25515980e-02
 -4.34493320e-03  2.25208756e-02  1.98086761e-02 -7.57428408e-02
 -4.36684722e-03  2.50829849e-02  2.59393621e-02 -3.07077523e-02
  7.04764426e-02  8.63500759e-02 -7.75880888e-02  1.59991793e-02
 -5.04692569e-02  4.88354899e-02  3.74992145e-03 -6.12969045e-04
 -3.87278087e-02 -2.32235175e-02 -3.63983698e-02 -5.07018808e-03
  1.10517563e-02 -3.26515324e-02  3.68386693e-02 -4.54949066e-02
 -1.18526735e-03  1.92689558e-03  2.18783561e-02  2.71092840e-02
 -4.06263992e-02  6.99159801e-02 -7.33282194e-02 -8.15294962e-03
 -1.42555386e-02  3.78036057e-03  1.20974347e-01 -6.68213218e-02
  3.05051319e-02  1.24480473e-02 -4.59294096e-02  1.03873145e-02
 -3.97977866e-02 -1.33042093e-02 -1.59402173e-02 -4.29347195e-02
  4.05275673e-02  7.07073808e-02 -4.50928956e-02 -3.62474434e-02
 -1.87589079e-02  1.60928499e-02  2.12657079e-02  6.70025349e-02
  3.25864032e-02  1.51125677e-02  3.20371725e-02 -1.35436086e-02
  2.31779832e-02 -1.13125890e-02  1.23795923e-02 -3.73516604e-02
  1.55545759e-03  2.15824638e-02 -3.49442475e-02 -2.97690630e-02
  2.32397504e-02 -1.25703337e-02 -1.09433038e-02 -8.87968838e-02
 -2.20183674e-02 -1.18423188e-02 -5.71083911e-02  3.91810052e-02
 -1.98827144e-02 -5.59270531e-02  7.60342041e-03  2.23641992e-02
 -1.86267197e-02  3.79805081e-02 -8.79655301e-04 -5.26199713e-02
  2.05066171e-03  1.72814894e-02 -4.84029017e-02 -1.87740307e-02
  1.54831795e-07  2.06594467e-02  3.03575322e-02  5.71854506e-03
 -5.33938147e-02 -2.46520955e-02  1.80340782e-02 -3.39978114e-02
  3.46506313e-05 -6.40035942e-02  2.50049364e-02 -2.04111692e-02
 -2.72036740e-03 -3.55961733e-02  2.71923002e-02  6.48940206e-02
  9.83431819e-04 -4.38490808e-02 -4.45297696e-02 -7.44892331e-03
  1.15205320e-02 -2.91253533e-03 -2.15495434e-02  2.84250360e-03
  4.29398753e-02 -6.09041266e-02 -7.86321983e-03 -3.90127604e-03
  2.47718333e-07  7.75885070e-04  7.47736692e-02  1.99317746e-03
 -6.07221061e-03  3.69210653e-02  2.78421137e-02 -5.64900115e-02
  1.61058921e-02 -9.50827450e-03 -2.60853302e-03 -2.45737284e-02
  1.91391166e-02  5.08195758e-02  2.61258781e-02 -1.03838071e-01
 -3.05815600e-02 -3.53345126e-02 -4.07038257e-02 -2.19843052e-02
 -2.24092435e-02  5.05567528e-02  7.22607374e-02  5.54789975e-02
  4.89433855e-02  3.37949768e-03 -6.84759840e-02  7.10322289e-03
  3.15672625e-03  4.78091836e-02 -7.19795302e-02 -3.30301970e-02
  3.19158845e-02  1.76429364e-03 -4.62790243e-02 -1.96378771e-02
  1.67493857e-02  4.73603755e-02 -2.09441390e-02  7.10246246e-03
  4.53146175e-02 -4.76523452e-02 -4.74881344e-02  1.00799901e-02
 -8.39593932e-02  3.36930193e-02 -3.72189321e-02  1.19432881e-02
 -3.16896364e-02 -1.29724620e-03 -1.55541031e-02  1.81728210e-02
 -1.49368439e-02 -1.70671716e-02 -4.19716798e-02  3.94658651e-03
 -2.24302132e-02  2.07292531e-02 -4.61415723e-02  8.50218628e-03
 -2.56864522e-02 -1.65337380e-02 -1.51846223e-02 -1.00041600e-02
  2.19642539e-02  2.61104722e-02  7.31359199e-02 -1.83709320e-02
  1.93979481e-34 -7.27933738e-03  5.96490083e-03  4.44310717e-02
  4.14822698e-02  1.12917209e-02 -1.93217490e-02  4.41879109e-02
 -8.93789623e-03  3.61119881e-02 -5.52125908e-02 -2.89572310e-02]
Embedding size: (768,)

Nice! We've now got a way to numerically represent each of our chunks.

Our embedding has a shape of `(768,)` meaning it's a vector of 768 numbers which represent our text in high-dimensional space, too many for a human to comprehend but machines love high-dimensional space.

> **Note:** No matter the size of the text input to our `all-mpnet-base-v2` model, it will be turned into an embedding size of `(768,)`. This value is fixed. So whether a sentence is 1 token long or 1000 tokens long, it will be truncated/padded with zeros to size 384 and then turned into an embedding vector of size `(768,)`. Of course, other embedding models may have different input/output shapes.

How about we add an embedding field to each of our chunk items?

Let's start by trying to create embeddings on the CPU, we'll time it with the `%%time` magic to see how long it takes.

In [ ]:
%%time

# Uncomment to see how long it takes to create embeddings on CPU
# # Make sure the model is on the CPU
# embedding_model.to("cpu")

# # Embed each chunk one by one
# for item in tqdm(pages_and_chunks_over_min_token_len):
#     item["embedding"] = embedding_model.encode(item["sentence_chunk"])

CPU times: total: 0 ns
Wall time: 0 ns

Ok not too bad... but this would take a *really* long time if we had a larger dataset.

Now let's see how long it takes to create the embeddings with a GPU.

In [ ]:
%%time

# Send the model to the GPU
embedding_model.to("cuda") # requires a GPU installed, for reference on my local machine, I'm using a NVIDIA RTX 4090

# Create embeddings one by one on the GPU
for item in tqdm(pages_and_chunks_over_min_token_len):
    item["embedding"] = embedding_model.encode(item["sentence_chunk"])

  0%|          | 0/1680 [00:00<?, ?it/s]

CPU times: total: 281 ms
Wall time: 12.2 s

Woah! Looks like the embeddings get created much faster (~10x faster on my machine) on the GPU!

You'll likely notice this trend with many of your deep learning workflows. If you have access to a GPU, especially a NVIDIA GPU, you should use one if you can.

But what if I told you we could go faster again?

You see many modern models can handle batched predictions.

This means computing on multiple samples at once.

Those are the types of operations where a GPU flourishes!

We can perform batched operations by turning our target text samples into a single list and then passing that list to our embedding model.

In [ ]:
# Turn text chunks into a single list
text_chunks = [item["sentence_chunk"] for item in pages_and_chunks_over_min_token_len]

In [ ]:
%%time

# Embed all texts in batches
text_chunk_embeddings = embedding_model.encode(text_chunks,
                                               batch_size=32, # you can use different batch sizes here for speed/performance, I found 32 works well for this use case
                                               convert_to_tensor=True) # optional to return embeddings as tensor instead of array

text_chunk_embeddings

CPU times: total: 1.17 s
Wall time: 3.21 s

tensor([[ 0.0674,  0.0902, -0.0051,  ..., -0.0221, -0.0232,  0.0126],
        [ 0.0552,  0.0592, -0.0166,  ..., -0.0120, -0.0103,  0.0227],
        [ 0.0280,  0.0340, -0.0206,  ..., -0.0054,  0.0213,  0.0313],
        ...,
        [ 0.0771,  0.0098, -0.0122,  ..., -0.0409, -0.0752, -0.0241],
        [ 0.1030, -0.0165,  0.0083,  ..., -0.0574, -0.0283, -0.0295],
        [ 0.0864, -0.0125, -0.0113,  ..., -0.0522, -0.0337, -0.0299]],
       device='cuda:0')

That's what I'm talking about!

A ~4x improvement (on my GPU) in speed thanks to batched operations.

So the tip here is to use a GPU when you can and use batched operations if you can too.

Now let's save our chunks and their embeddings so we could import them later if we wanted.

### Save embeddings to file

Since creating embeddings can be a timely process (not so much for our case but it can be for more larger datasets), let's turn our `pages_and_chunks_over_min_token_len` list of dictionaries into a DataFrame and save it.

In [ ]:
# Save embeddings to file
text_chunks_and_embeddings_df = pd.DataFrame(pages_and_chunks_over_min_token_len)
embeddings_df_save_path = "text_chunks_and_embeddings_df.csv"
text_chunks_and_embeddings_df.to_csv(embeddings_df_save_path, index=False)

And we can make sure it imports nicely by loading it.

In [ ]:
# Import saved file and view
text_chunks_and_embedding_df_load = pd.read_csv(embeddings_df_save_path)
text_chunks_and_embedding_df_load.head()

,page_number,sentence_chunk,chunk_char_count,chunk_word_count,chunk_token_count,embedding
0,-39,Human Nutrition: 2020 Edition UNIVERSITY OF HA...,308,42,77.00,[ 6.74242675e-02 9.02281553e-02 -5.09548280e-...
1,-38,Human Nutrition: 2020 Edition by University of...,210,30,52.50,[ 5.52156307e-02 5.92139475e-02 -1.66167468e-...
2,-37,Contents Preface University of Hawai‘i at Māno...,766,116,191.50,[ 2.79801842e-02 3.39813866e-02 -2.06426680e-...
3,-36,Lifestyles and Nutrition University of Hawai‘i...,941,144,235.25,[ 6.82566985e-02 3.81275080e-02 -8.46853852e-...
4,-35,The Cardiovascular System University of Hawai‘...,998,152,249.50,[ 3.30264494e-02 -8.49768054e-03 9.57158953e-...

### Chunking and embedding questions

> **Which embedding model should I use?**

This depends on many factors. My best advice is to experiment, experiment, experiment!

If you want the model to run locally, you'll have to make sure it's feasible to run on your own hardware.

A good place to see how different models perform on a wide range of embedding tasks is the [Hugging Face Massive Text Embedding Benchmark (MTEB) Leaderboard](https://huggingface.co/spaces/mteb/leaderboard).

> **What other forms of text chunking/splitting are there?**

There are a fair few options here too. We've kept it simple with groups of sentences.

For more, [Pinecone has a great guide on different kinds of chunking](https://www.pinecone.io/learn/chunking-strategies/) including for different kinds of data such as markdown and LaTeX.

Libraries such as [LangChain also have a good amount of in-built text splitting options](https://python.langchain.com/docs/modules/data_connection/document_transformers/).

> **What should I think about when creating my embeddings?**

Our model turns text inputs up to 384 tokens long in embedding vectors of size 768.

Generally, the larger the vector size, the more information that gets encoded into the embedding (however, this is not always the case, as smaller, better models can outperform larger ones).

Though with larger vector sizes comes larger storage and compute requirements.

Our model is also relatively small (420MB) in size compared to larger models that are available.

Larger models may result in better performance but will also require more compute.

So some things to think about:
* Size of input - If you need to embed longer sequences, choose a model with a larger input capacity.
* Size of embedding vector - Larger is generally a better representation but requires more compute/storage.
* Size of model - Larger models generally result in better embeddings but require more compute power/time to run.
* Open or closed - Open models allow you to run them on your own hardware whereas closed models can be easier to setup but require an API call to get embeddings.

> **Where should I store my embeddings?**

If you've got a relatively small dataset, for example, under 100,000 examples (this number is rough and only based on first hand experience), `np.array` or `torch.tensor` can work just fine as your dataset.

But if you've got a production system and want to work with 100,000+ embeddings, you may want to look into a [vector database]( https://en.wikipedia.org/wiki/Vector_database) (these have become very popular lately and there are many offerings).

### Document Ingestion and Embedding Creation Extensions

One major extension to the workflow above would to functionize it.

Or turn it into a script.

As in, take all the functionality we've created and package it into a single process (e.g. go from document -> embeddings file).

So you could input a document on one end and have embeddings come out the other end. The hardest part of this is knowing what kind of preprocessing your text may need before it's turned into embeddings. Cleaner text generally means better results.